# Site wide configuration

title: Brouilleurs de blanc
locale: fr_BE
description: un groupe.  de l'encre, de la terre et de la lumière.  un thème qui se déploie au gré des lettres, des mots et des images.  du blanc qui prend forme au fil des rêveries qui se croisent, se mélangent et se répondent.

logo: site-logo.png
search: false
url: https://brouilleursdeblanc.org

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Brouilleurs de blanc
  avatar: bio-photo.jpg
  email: info@brouilleursdeblanc.org
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
